package:
  name: aimio
  version: {{ GIT_DESCRIBE_TAG | lower | replace("v","") }}

source:
  path: ./../../

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.2
    - boost >=1.57
    - ninja
    - gtest
    - n88util >=3.0
  host:
    - libcxx <=14.0.6
  run:
    - boost >=1.57
    - n88util >=3.0

about:
  home: https://github.com/Numerics88/AimIO
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'SCANCO AIM input/output library'
  description: |
    AimIO is a simple C++ class for reading and writing Scanco AIM image files.
  dev_url: https://github.com/Numerics88/AimIO
