package:
  name: aimio
  version: 2.0.0

source:
  path: ./../../

build:
  number: 0

requirements:
  build:
    - cmake >=3.30.3
    - boost >=1.56
    - ninja
    - gtest
    - n88util >=3.0
    - {{ compiler('cxx') }}
  host:
    - boost >=1.56

about:
  home: https://github.com/Numerics88/AimIO
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "SCANCO AIM input/output library"
  description: |
    AimIO is a simple C++ class for reading and writing Scanco AIM image files.
  dev_url: https://github.com/Numerics88/AimIO
